/*
using System;

namespace Extenity.UnityEditorToolbox
{

	public class AutogeneratedSceneModificationPreventer : UnityEditor.AssetModificationProcessor
	{
		public static string[] OnWillSaveAssets(string[] paths)
		{
			if (paths.IsNullOrEmpty())
				return paths;

			if (IsProcessorRunning)
			{
				//Log.Info("Skipping backup scene modification checks.");
				return paths;
			}

			//Log.Info("Saving assets: \n" + paths.Serialize('\n'));

			for (var i = 0; i < paths.Length; i++)
			{
				var path = paths[i];
				if (path.EndsWith(".unity"))
				{
					var sceneName = Path.GetFileNameWithoutExtension(path);
					if (sceneName.EndsWith(ProcessedScenePostfix))
					{
						EditorUtility.DisplayDialog(
							"Warning!",
							"You are working on an automatically generated scene which will be overwritten on build. Make sure you do know what you are doing.",
							"Okay, got it! I promise!");
					}
				}
			}

			return paths;
		}
	}

}

*/
