using UnityEngine;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Extenity.AssetToolbox.Editor;
using Extenity.DataToolbox;
using Extenity.DataToolbox.Editor;
using Extenity.FileSystemToolbox;
using Extenity.ParallelToolbox;
using UnityEditor;

namespace Extenity.UnityEditorToolbox.Editor
{

	public static class CleanUp
	{
		#region Configuration

		private const string Menu = ExtenityMenu.CleanUp;

		public static string[] IgnoredDirectories =
		{
			".hg",
			".git",
		};

		private static readonly string OrigFileFilter = "*.orig";
		private static readonly string ThumbsDBFileFilter = "thumbs.db";
		private static readonly string DSStoreFileFilter = ".DS_Store";

		#endregion

		#region Cleanup at Editor launch

		private static BoolEditorPref EnableRunAtEditorLaunch => new("Extenity.RunCleanupAtEditorLaunch",
		                                                             PathHashPostfix.Yes,
		                                                             DefaultValueMethod<bool>.Value(true), 
		                                                             EditorPrefLogOptions.NoLogging);

		[InitializeOnEditorLaunchMethod]
		private static void RunAtEditorLaunch()
		{
			_RunAtEditorLaunch().FireAndForget();
		}

		private static async Task _RunAtEditorLaunch()
		{
			if (EnableRunAtEditorLaunch.Value)
			{
				await DoClearAllNonDestructiveFiles();
			}
		}

		#endregion

		#region Empty directories

		private static List<string> GetEmptyDirectories()
		{
			return GetEmptyDirectories(Application.dataPath);
		}

		private static List<string> GetEmptyDirectories(string path)
		{
			var list = new List<string>();
			var subDirectories = Directory.GetDirectories(path, "*", SearchOption.AllDirectories);

			for (int iSubDirectory = 0; iSubDirectory < subDirectories.Length; iSubDirectory++)
			{
				var subDirectory = subDirectories[iSubDirectory].FixDirectorySeparatorChars();
				if (DirectoryTools.IsDirectoryEmpty(subDirectory))
				{
					var directoryNames = subDirectory.Split(PathTools.DirectorySeparatorChar);
					if (!directoryNames.Any(item => IgnoredDirectories.Contains(item)))
					{
						list.Add(subDirectory);
					}
				}
			}

			return list;
		}

		#endregion

		#region Clear Files and Directories

		private static async Task DoClearFiles(string fileNameFilter, bool refreshAssetDatabase)
		{
			int progressId = Progress.Start("Clear thumbs.db files");
			await Task.Yield();

			var path = Application.dataPath;
			var items = Directory.GetFiles(path, fileNameFilter, SearchOption.AllDirectories);
			for (int i = 0; i < items.Length; i++)
			{
				AssetDatabaseTools.ManuallyDeleteMetaFileAndAsset(items[i]);
				Progress.Report(progressId, (float)(i + 1) / items.Length);
				await Task.Yield();
			}

			if (items.Length > 0)
			{
				items.LogList($"Cleared '{items.Length}' files with filter '{fileNameFilter}':");

				if (refreshAssetDatabase)
				{
					AssetDatabase.Refresh();
				}
			}

			Progress.Remove(progressId);
			await Task.Yield();
		}

		private static async Task DoClearEmptyDirectories(bool refreshAssetDatabase)
		{
			int progressId = Progress.Start("Clear empty directories");
			await Task.Yield();

			var tryAgain = true;
			var clearedItems = new List<string>();

			while (tryAgain)
			{
				var items = GetEmptyDirectories();
				for (int i = 0; i < items.Count; i++)
				{
					AssetDatabaseTools.ManuallyDeleteMetaFileAndAsset(items[i]);
					clearedItems.AddSorted(items[i]);
					Progress.Report(progressId, (float)(i + 1) / items.Count); // This is not the correct way to display the progress, but it's better than nothing.
					await Task.Yield();
				}

				tryAgain = items.Count > 0;
			}

			if (clearedItems.Count > 0)
			{
				clearedItems.LogList($"Cleared '{clearedItems.Count}' empty directories:");

				if (refreshAssetDatabase)
				{
					AssetDatabase.Refresh();
				}
			}

			Progress.Remove(progressId);
			await Task.Yield();
		}

		/// <summary>
		/// Note that this deliberately does NOT use AssetDatabase deletion or filter out IgnoredDirectories.
		/// '.DS_Store' files are hidden, have no '.meta' file, and live all over the project (including Temp,
		/// Library and '.git'), so they are deleted with a plain FileTools.Delete that scans from the project
		/// root.
		/// </summary>
		private static async Task DoClearDSStoreFiles()
		{
			if (!EditorUtility.DisplayDialog(
				    "Clear .DS_Store files",
				    "This permanently deletes all '.DS_Store' files across the entire project directory.\n\n" +
				    "'.DS_Store' files store per-folder Finder view state (icon positions, window size) as the user " +
				    "navigates these directories in Finder. These files will be regenerated by macOS.\n\n" +
				    "This cannot be undone.",
				    "Delete",
				    "Cancel"))
			{
				return;
			}

			int progressId = Progress.Start("Clear .DS_Store files");
			await Task.Yield();

			var path = Directory.GetParent(Application.dataPath).FullName;
			var items = Directory.GetFiles(path, DSStoreFileFilter, SearchOption.AllDirectories);
			for (int i = 0; i < items.Length; i++)
			{
				FileTools.Delete(items[i]);
				Progress.Report(progressId, (float)(i + 1) / items.Length);
				await Task.Yield();
			}

			if (items.Length > 0)
			{
				items.LogList($"Cleared '{items.Length}' .DS_Store files:");
			}

			Progress.Remove(progressId);
			await Task.Yield();
		}

		/// <summary>
		/// Clears only the non-destructive files that is safe to delete unattended (including at editor launch).
		/// The destructive '.DS_Store' cleaner is deliberately excluded.
		/// </summary>
		private static async Task DoClearAllNonDestructiveFiles()
		{
			await DoClearFiles(OrigFileFilter, false);
			await DoClearFiles(ThumbsDBFileFilter, false);
			await DoClearEmptyDirectories(true);
			// await DoClearDSStoreFiles(); This is skipped. It's considered as destructive, since it contains Finder configuration of the user.
		}

		private static async Task DoClearAllIncludingDestructiveFiles()
		{
			await DoClearAllNonDestructiveFiles();
			await DoClearDSStoreFiles();
		}

		#endregion

		#region Menu

		[MenuItem(Menu + "Clear all (non-destructive)", priority = ExtenityMenu.CleanUpPriority + 1)]
		public static void ClearAllNonDestructiveFiles()
		{
			DoClearAllNonDestructiveFiles().FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Clear all (including destructive)", priority = ExtenityMenu.CleanUpPriority + 2)]
		public static void ClearAllIncludingDestructiveFiles()
		{
			DoClearAllIncludingDestructiveFiles().FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Clear .orig files", priority = ExtenityMenu.CleanUpPriority + 21)]
		public static void ClearOrigFiles()
		{
			DoClearFiles(OrigFileFilter, true).FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Clear thumbs.db files", priority = ExtenityMenu.CleanUpPriority + 22)]
		public static void ClearThumbsDbFiles()
		{
			DoClearFiles(ThumbsDBFileFilter, true).FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Clear empty directories", priority = ExtenityMenu.CleanUpPriority + 23)]
		public static void ClearEmptyDirectories()
		{
			DoClearEmptyDirectories(true).FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Clear .DS_Store files", priority = ExtenityMenu.CleanUpPriority + 24)]
		public static void ClearDSStoreFiles()
		{
			DoClearDSStoreFiles().FireAndForgetAndContinue(() => Log.Info("Cleanup finished."));
		}

		[MenuItem(Menu + "Auto Cleanup at Editor launch/Enable", priority = ExtenityMenu.CleanUpPriority + 41)]
		public static void EnableAutoCleanUpAtEditorLaunch()
		{
			EnableRunAtEditorLaunch.Value = true;
		}

		[MenuItem(Menu + "Auto Cleanup at Editor launch/Enable", validate = true)]
		public static bool EnableAutoCleanUpAtEditorLaunch_Validate()
		{
			return !EnableRunAtEditorLaunch.Value;
		}

		[MenuItem(Menu + "Auto Cleanup at Editor launch/Disable", priority = ExtenityMenu.CleanUpPriorityEnd)]
		public static void DisableAutoCleanUpAtEditorLaunch()
		{
			EnableRunAtEditorLaunch.Value = false;
		}

		[MenuItem(Menu + "Auto Cleanup at Editor launch/Disable", validate = true)]
		public static bool DisableAutoCleanUpAtEditorLaunch_Validate()
		{
			return EnableRunAtEditorLaunch.Value;
		}

		#endregion

		#region Log

		private static readonly Logger Log = new(nameof(CleanUp));

		#endregion
	}

}
